"""add authors table and book.author_id fk

Revision ID: 77a24bd5c01e
Revises: 9c64d9405391
Create Date: 2026-03-20 22:17:29.203829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a24bd5c01e'
down_revision: Union[str, Sequence[str], None] = '9c64d9405391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
